"""initial schema

Revision ID: 55ad9986bb5b
Revises: 
Create Date: 2026-08-17 16:55:55.461209

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55ad9986bb5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rent_cold', sa.Float(), nullable=True),
    sa.Column('rent_warm', sa.Float(), nullable=True),
    sa.Column('rent_warm_is_estimated', sa.Boolean(), nullable=False),
    sa.Column('utilities', sa.Float(), nullable=True),
    sa.Column('heating_cost', sa.Float(), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('size_sqm', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Float(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('floor', sa.String(length=32), nullable=True),
    sa.Column('furnished', sa.Enum('FURNISHED', 'PARTIALLY', 'UNFURNISHED', 'UNKNOWN', name='furnishedstatus'), nullable=False),
    sa.Column('kitchen', sa.Boolean(), nullable=True),
    sa.Column('private_kitchen', sa.Boolean(), nullable=True),
    sa.Column('private_bathroom', sa.Boolean(), nullable=True),
    sa.Column('balcony', sa.Boolean(), nullable=True),
    sa.Column('anmeldung', sa.Enum('POSSIBLE', 'IMPOSSIBLE', 'UNKNOWN', name='anmeldungstatus'), nullable=False),
    sa.Column('availability_date', sa.DateTime(), nullable=True),
    sa.Column('rental_type', sa.Enum('LONG_TERM', 'TEMPORARY', 'ZWISCHENMIETE', 'UNKNOWN', name='rentaltype'), nullable=False),
    sa.Column('contact_name', sa.String(length=128), nullable=True),
    sa.Column('contact_company', sa.String(length=128), nullable=True),
    sa.Column('contact_url', sa.String(length=1024), nullable=True),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('notification_count', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('match_explanation', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'MATCHED', 'NOTIFIED', 'UPDATED', 'EXPIRED', 'REMOVED', 'REJECTED', name='listingstatus'), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_content_hash'), 'listings', ['content_hash'], unique=False)
    op.create_table('search_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('preferred_districts', sa.JSON(), nullable=False),
    sa.Column('nearby_areas', sa.JSON(), nullable=False),
    sa.Column('max_rent_warm', sa.Float(), nullable=False),
    sa.Column('min_size_sqm', sa.Float(), nullable=False),
    sa.Column('preferred_size_min', sa.Float(), nullable=False),
    sa.Column('preferred_size_max', sa.Float(), nullable=False),
    sa.Column('max_rooms', sa.Float(), nullable=False),
    sa.Column('available_from', sa.DateTime(), nullable=True),
    sa.Column('anmeldung_preference', sa.String(length=32), nullable=False),
    sa.Column('notification_mode', sa.String(length=32), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_score_to_notify', sa.Integer(), nullable=False),
    sa.Column('scoring_weights', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('total_discovered', sa.Integer(), nullable=False),
    sa.Column('total_parsed', sa.Integer(), nullable=False),
    sa.Column('total_matching', sa.Integer(), nullable=False),
    sa.Column('total_new', sa.Integer(), nullable=False),
    sa.Column('total_duplicates_merged', sa.Integer(), nullable=False),
    sa.Column('source_results', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('OK', 'LIMITED', 'ERROR', 'DISABLED', name='sourcestatus'), nullable=False),
    sa.Column('unavailable_reason', sa.Text(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('last_listings_found', sa.Integer(), nullable=False),
    sa.Column('last_matching_found', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_key'), 'sources', ['key'], unique=True)
    op.create_table('listing_source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('source_listing_id', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key', 'source_listing_id', name='uq_source_listing')
    )
    op.create_index(op.f('ix_listing_source_records_listing_id'), 'listing_source_records', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_source_records_source_key'), 'listing_source_records', ['source_key'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_listing_source_records_source_key'), table_name='listing_source_records')
    op.drop_index(op.f('ix_listing_source_records_listing_id'), table_name='listing_source_records')
    op.drop_table('listing_source_records')
    op.drop_index(op.f('ix_sources_key'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('search_runs')
    op.drop_table('search_profiles')
    op.drop_index(op.f('ix_listings_content_hash'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
